/*
 * Spike S-2 — the scene being rendered.
 *
 * Adapted from the S-1 harness (PR #46, commit 04e6149), which built the same
 * §7 components for a heap measurement. Three things are different here, and
 * each of them is a render cost S-1 could not see:
 *
 *   1. Real fonts. S-1 used built-in Montserrat and said so; the §8 type scale
 *      and the two §7.1 icon sizes are bpp:4 faces whose glyph cache is a
 *      render-time cost. This is where that shows up.
 *   2. Tiles keep handles to the widgets that change, because §5.2 delivers
 *      state diffs and the runtime updates a label rather than rebuilding a
 *      tile. Measuring a rebuild per update would measure the wrong thing.
 *   3. Animations run continuously on four tiles, per the issue's scope.
 */

#include <stdio.h>
#include <string.h>

#include "s2_board.h"
#include "s2_icons.h"
#include "s2_scene.h"

/*
 * A short description of the build, shown on the panel. Assembled from the same
 * macros that configure the run.
 *
 * s2_board.h is included above for exactly one reason: S2_VSYNC_GATE is defined
 * there, and without the include the preprocessor here saw it as undefined and
 * cheerfully labelled a gated build "nogate". The tag exists to remove doubt
 * about which build is on the panel, so a tag that can lie is worse than none —
 * it was caught by the maintainer reading a label that contradicted the run.
 * Everything else in the tag comes from -D flags on the command line, which is
 * why the rest of it was right.
 */
#if S2_NUM_FBS >= 2
#define S2_TAG_FB "2FB"
#else
#define S2_TAG_FB "1FB"
#endif
#if S2_VSYNC_GATE
#define S2_TAG_GATE "/gate"
#else
#define S2_TAG_GATE "/nogate"
#endif
#if S2_BOUNCE
#define S2_TAG_BOUNCE "/bounce"
#else
#define S2_TAG_BOUNCE "/NOBOUNCE"
#endif
#if S2_RADIO
#define S2_TAG_RADIO "/radio"
#else
#define S2_TAG_RADIO ""
#endif
#ifdef S2_TAG_OVERRIDE
/*
 * A blind label, for the one comparison where the observer knowing the answer
 * would contaminate it. The bounce buffer question (§6.2) came down to a single
 * subjective judgement, and by the time it was asked the maintainer already knew
 * which configuration the spike was recommending. Overriding the tag with "A" or
 * "B" lets the same two builds be shown without saying which is which.
 */
#define S2_BUILD_TAG S2_TAG_OVERRIDE
#else
#define S2_BUILD_TAG S2_TAG_FB S2_TAG_GATE S2_TAG_BOUNCE S2_TAG_RADIO
#endif

/* Generated by tools/fonts/generate.sh — see main/CMakeLists.txt. */
extern const lv_font_t slate_font_hero_44;
extern const lv_font_t slate_font_body_20;
extern const lv_font_t slate_font_caption_15;
extern const lv_font_t slate_font_icons_28;
extern const lv_font_t slate_font_icons_48;

/* §13: "20 tiles including 4 animated". Only light and cover have an animated
 * variant, so the four are counted among those rather than taken by index. */
#define S2_ANIMATED_TILES 4

/* design.md §3.2 */
#define S2_SCREEN_W 800
#define S2_SCREEN_H 480
#define S2_BAR_H     56
#define S2_GAP       12
#define S2_MARGIN    14

#define S2_CONTENT_H (S2_SCREEN_H - S2_BAR_H)
#define S2_CELL_W    ((S2_SCREEN_W - 2 * S2_MARGIN - (S2_GRID_COLS - 1) * S2_GAP) / S2_GRID_COLS)
#define S2_CELL_H    ((S2_CONTENT_H - 2 * S2_MARGIN - (S2_GRID_ROWS - 1) * S2_GAP) / S2_GRID_ROWS)

/* Midnight theme tokens — design.md §8. */
#define S2_COL_BG          0x101114
#define S2_COL_SURFACE     0x1A1C21
#define S2_COL_SURFACE_ALT 0x22252B
#define S2_COL_TEXT_HI     0xF2F5F9
#define S2_COL_TEXT_LO     0x8A94A6
#define S2_COL_ACCENT      0x6C8CFF
#define S2_COL_WARN        0xF5A524
#define S2_RADIUS          18

typedef enum {
    S2_LIGHT,
    S2_COVER,
    S2_SENSOR,
    S2_SCENE,
    S2_UNKNOWN,
} s2_type_t;

/* What an entity update can reach. NULL means this tile has no such widget. */
typedef struct {
    s2_type_t type;
    lv_obj_t *tile;
    lv_obj_t *icon;
    lv_obj_t *value;   /* sensor value / light brightness % */
    lv_obj_t *slider;  /* light brightness, cover position */
    lv_obj_t *bar;     /* cover position indicator */
    const char *unit;
} s2_tile_t;

static s2_tile_t s_tiles[S2_TILES];
static uint32_t  s_tile_count;

/* -------------------------------------------------------------------------
 * Deterministic scene definition
 *
 * Seeded from the page index so a page looks the same on every run and a bad
 * frame can be re-run. The mix is fixed rather than random: unlike S-1, which
 * needed varying trees to defeat allocator reuse, this spike wants the same
 * scene across builds so that 1-vs-2 framebuffers is the only thing that
 * differs between two runs.
 * ------------------------------------------------------------------------- */

typedef struct {
    s2_type_t   type;
    uint8_t     w, h;
    const char *label;
    const char *icon;
} s2_recipe_t;

static const s2_recipe_t S2_RECIPES[] = {
    { S2_LIGHT,   2, 1, "Living room",                           S2_ICON_LIGHTBULB_ON },
    { S2_SENSOR,  1, 1, "Temperature",                           S2_ICON_THERMOMETER },
    { S2_COVER,   1, 2, "Blind",                                 S2_ICON_WINDOW_SHUTTER },
    { S2_LIGHT,   1, 1, "Kitchen",                               S2_ICON_CEILING_LIGHT },
    { S2_SENSOR,  2, 1, "Pressure",                              S2_ICON_GAUGE },
    { S2_SCENE,   1, 1, "Relax",                                 S2_ICON_SOFA_OUTLINE },
    { S2_LIGHT,   1, 1, "Bedroom ceiling downlights and cove",   S2_ICON_LIGHTBULB_OUTLINE },
    { S2_SENSOR,  1, 1, "Humidity",                              S2_ICON_WATER_PERCENT },
    { S2_COVER,   2, 1, "Study",                                 S2_ICON_WINDOW_SHUTTER_OPEN },
    { S2_SCENE,   1, 1, "Movie",                                 S2_ICON_MOVIE_OPEN_OUTLINE },
    { S2_SENSOR,  1, 1, "Outside",                               S2_ICON_WEATHER_SUNNY },
    { S2_LIGHT,   1, 1, "Hall",                                  S2_ICON_LIGHTBULB_OUTLINE },
    { S2_SCENE,   1, 1, "Night",                                 S2_ICON_SLEEP },
    { S2_UNKNOWN, 1, 1, "thermostat",                            S2_ICON_HELP_CIRCLE_OUTLINE },
    { S2_SENSOR,  1, 1, "CO2",                                   S2_ICON_GAUGE },
    { S2_SCENE,   1, 1, "Morning",                               S2_ICON_COFFEE_OUTLINE },
    { S2_LIGHT,   1, 1, "Desk",                                  S2_ICON_LIGHTBULB_ON },
    { S2_SENSOR,  1, 1, "Power",                                 S2_ICON_GAUGE },
    { S2_COVER,   1, 1, "Garage",                                S2_ICON_WINDOW_SHUTTER },
    { S2_SENSOR,  1, 1, "Battery",                               S2_ICON_GAUGE },
    { S2_LIGHT,   1, 1, "Porch",                                 S2_ICON_LIGHTBULB_OUTLINE },
    { S2_SENSOR,  1, 1, "Wind",                                  S2_ICON_WEATHER_SUNNY },
};
#define S2_RECIPE_COUNT (sizeof(S2_RECIPES) / sizeof(S2_RECIPES[0]))

/* -------------------------------------------------------------------------
 * Animations (§7.2 movement indicator, §7.5 pending state)
 * ------------------------------------------------------------------------- */

static void s2_opa_anim_cb(void *var, int32_t v)
{
    lv_obj_set_style_opa((lv_obj_t *)var, (lv_opa_t)v, LV_PART_MAIN);
}

static void s2_arc_anim_cb(void *var, int32_t v)
{
    lv_bar_set_value((lv_obj_t *)var, v, LV_ANIM_OFF);
}

static void s2_start_pulse(lv_obj_t *obj, uint32_t period_ms)
{
    lv_anim_t a;
    lv_anim_init(&a);
    lv_anim_set_var(&a, obj);
    lv_anim_set_exec_cb(&a, s2_opa_anim_cb);
    lv_anim_set_values(&a, LV_OPA_40, LV_OPA_COVER);
    lv_anim_set_duration(&a, period_ms);
    lv_anim_set_reverse_duration(&a, period_ms);
    lv_anim_set_repeat_count(&a, LV_ANIM_REPEAT_INFINITE);
    lv_anim_start(&a);
}

static void s2_start_travel(lv_obj_t *bar)
{
    lv_anim_t a;
    lv_anim_init(&a);
    lv_anim_set_var(&a, bar);
    lv_anim_set_exec_cb(&a, s2_arc_anim_cb);
    lv_anim_set_values(&a, 0, 100);
    lv_anim_set_duration(&a, 2400);
    lv_anim_set_reverse_duration(&a, 2400);
    lv_anim_set_repeat_count(&a, LV_ANIM_REPEAT_INFINITE);
    lv_anim_start(&a);
}

/* -------------------------------------------------------------------------
 * Components
 * ------------------------------------------------------------------------- */

static lv_obj_t *s2_icon_label(lv_obj_t *parent, const char *glyph, bool large, uint32_t colour)
{
    lv_obj_t *icon = lv_label_create(parent);
    lv_label_set_text(icon, glyph);
    lv_obj_set_style_text_font(icon, large ? &slate_font_icons_48 : &slate_font_icons_28,
                               LV_PART_MAIN);
    lv_obj_set_style_text_color(icon, lv_color_hex(colour), LV_PART_MAIN);
    return icon;
}

/* §7.5: a name that does not fit is marquee-scrolled, never clipped. The
 * scrolling label is also a per-frame invalidation, which is a render cost that
 * a static label would not have and that a real dashboard will have. */
static lv_obj_t *s2_name_label(lv_obj_t *parent, const char *text, int32_t width)
{
    lv_obj_t *label = lv_label_create(parent);
    lv_label_set_text(label, text);
    lv_label_set_long_mode(label, LV_LABEL_LONG_MODE_SCROLL_CIRCULAR);
    lv_obj_set_width(label, width);
    lv_obj_set_style_text_font(label, &slate_font_caption_15, LV_PART_MAIN);
    lv_obj_set_style_text_color(label, lv_color_hex(S2_COL_TEXT_LO), LV_PART_MAIN);
    return label;
}

static void s2_build_light(s2_tile_t *t, int32_t w, int32_t h, const s2_recipe_t *r, bool animated)
{
    t->icon = s2_icon_label(t->tile, r->icon, r->w >= 2 && r->h >= 2, S2_COL_WARN);
    lv_obj_align(t->icon, LV_ALIGN_TOP_LEFT, 0, 0);

    lv_obj_t *name = s2_name_label(t->tile, r->label, w - 2 * S2_MARGIN);
    lv_obj_align(name, LV_ALIGN_BOTTOM_LEFT, 0, 0);

    /* §7.1: 2×1 and larger carry a brightness percentage and a slider. */
    if (r->w >= 2) {
        t->value = lv_label_create(t->tile);
        lv_label_set_text(t->value, "62%");
        lv_obj_set_style_text_font(t->value, &slate_font_body_20, LV_PART_MAIN);
        lv_obj_set_style_text_color(t->value, lv_color_hex(S2_COL_TEXT_HI), LV_PART_MAIN);
        lv_obj_align(t->value, LV_ALIGN_TOP_RIGHT, 0, 0);

        t->slider = lv_slider_create(t->tile);
        lv_obj_set_size(t->slider, w - 2 * S2_MARGIN, 12);
        lv_obj_align(t->slider, LV_ALIGN_CENTER, 0, h / 8);
        lv_slider_set_value(t->slider, 62, LV_ANIM_OFF);
        lv_obj_set_style_bg_color(t->slider, lv_color_hex(S2_COL_SURFACE_ALT), LV_PART_MAIN);
        lv_obj_set_style_bg_color(t->slider, lv_color_hex(S2_COL_ACCENT), LV_PART_INDICATOR);
    }

    /* §7.5: every action shows a pending state. */
    if (animated) {
        s2_start_pulse(t->icon, 700);
    }
}

static void s2_build_cover(s2_tile_t *t, int32_t w, int32_t h, const s2_recipe_t *r, bool animated)
{
    t->icon = s2_icon_label(t->tile, r->icon, false, S2_COL_TEXT_HI);
    lv_obj_align(t->icon, LV_ALIGN_TOP_LEFT, 0, 0);

    lv_obj_t *name = s2_name_label(t->tile, r->label, w - 2 * S2_MARGIN);
    lv_obj_align(name, LV_ALIGN_BOTTOM_LEFT, 0, 0);

    /* §7.2: up / stop / down, §7.5: touch targets ≥ 48 px. */
    static const char *glyphs[] = { S2_ICON_ARROW_UP, S2_ICON_STOP, S2_ICON_ARROW_DOWN };
    const bool vertical = r->h >= 2;
    for (int i = 0; i < 3; i++) {
        lv_obj_t *btn = lv_button_create(t->tile);
        lv_obj_set_size(btn, 48, 48);
        lv_obj_align(btn, vertical ? LV_ALIGN_TOP_MID : LV_ALIGN_LEFT_MID,
                     vertical ? 0 : (int32_t)i * 52,
                     vertical ? 30 + (int32_t)i * 52 : 0);
        lv_obj_set_style_bg_color(btn, lv_color_hex(S2_COL_SURFACE_ALT), LV_PART_MAIN);
        lv_obj_set_style_radius(btn, S2_RADIUS / 2, LV_PART_MAIN);
        lv_obj_t *sym = lv_label_create(btn);
        lv_label_set_text(sym, glyphs[i]);
        lv_obj_set_style_text_font(sym, &slate_font_icons_28, LV_PART_MAIN);
        lv_obj_center(sym);
    }

    /* §7.2: movement shows an animated indicator until the state settles. */
    t->bar = lv_bar_create(t->tile);
    lv_obj_set_size(t->bar, w - 2 * S2_MARGIN, 6);
    lv_obj_align(t->bar, LV_ALIGN_BOTTOM_MID, 0, -18);
    lv_bar_set_range(t->bar, 0, 100);
    lv_bar_set_value(t->bar, 40, LV_ANIM_OFF);
    lv_obj_set_style_bg_color(t->bar, lv_color_hex(S2_COL_SURFACE_ALT), LV_PART_MAIN);
    lv_obj_set_style_bg_color(t->bar, lv_color_hex(S2_COL_ACCENT), LV_PART_INDICATOR);
    if (animated) {
        s2_start_travel(t->bar);
    }
    (void)h;
}

static void s2_build_sensor(s2_tile_t *t, int32_t w, const s2_recipe_t *r)
{
    t->value = lv_label_create(t->tile);
    lv_label_set_text(t->value, "21.4");
    /* §8: hero 44 for the value. §7.5 out-of-range: a longer string steps the
     * type scale down rather than overflowing — s2_scene_update() exercises both
     * branches, and they cost different amounts of glyph work. */
    lv_obj_set_style_text_font(t->value, &slate_font_hero_44, LV_PART_MAIN);
    lv_obj_set_style_text_color(t->value, lv_color_hex(S2_COL_TEXT_HI), LV_PART_MAIN);
    lv_obj_align(t->value, LV_ALIGN_LEFT_MID, 0, -6);

    if (r->w >= 2) {
        t->icon = s2_icon_label(t->tile, r->icon, false, S2_COL_TEXT_LO);
        lv_obj_align(t->icon, LV_ALIGN_TOP_RIGHT, 0, 0);
    }

    lv_obj_t *name = s2_name_label(t->tile, r->label, w - 2 * S2_MARGIN);
    lv_obj_align(name, LV_ALIGN_BOTTOM_LEFT, 0, 0);
    t->unit = "°C";
}

static void s2_build_scene(s2_tile_t *t, int32_t w, const s2_recipe_t *r)
{
    t->icon = s2_icon_label(t->tile, r->icon, false, S2_COL_ACCENT);
    lv_obj_align(t->icon, LV_ALIGN_CENTER, 0, -12);

    lv_obj_t *name = s2_name_label(t->tile, r->label, w - 2 * S2_MARGIN);
    lv_obj_align(name, LV_ALIGN_BOTTOM_MID, 0, 0);
}

/* §3.1: an unknown component type renders a placeholder, never a crash. */
static void s2_build_unknown(s2_tile_t *t, const s2_recipe_t *r)
{
    t->icon = s2_icon_label(t->tile, S2_ICON_HELP_CIRCLE_OUTLINE, false, S2_COL_WARN);
    lv_obj_align(t->icon, LV_ALIGN_CENTER, 0, -12);

    lv_obj_t *label = lv_label_create(t->tile);
    lv_label_set_text(label, r->label);
    lv_label_set_long_mode(label, LV_LABEL_LONG_MODE_DOTS);
    lv_obj_set_width(label, lv_pct(100));
    lv_obj_set_style_text_font(label, &slate_font_caption_15, LV_PART_MAIN);
    lv_obj_set_style_text_color(label, lv_color_hex(S2_COL_WARN), LV_PART_MAIN);
    lv_obj_align(label, LV_ALIGN_BOTTOM_MID, 0, 0);
}

/* -------------------------------------------------------------------------
 * Page build and destroy — the §6.4 PUT /config path
 * ------------------------------------------------------------------------- */

lv_obj_t *s2_scene_build(uint32_t index)
{
    memset(s_tiles, 0, sizeof(s_tiles));
    s_tile_count = 0;

    lv_obj_t *screen = lv_screen_active();
    lv_obj_set_style_bg_color(screen, lv_color_hex(S2_COL_BG), LV_PART_MAIN);

    lv_obj_t *root = lv_obj_create(screen);
    lv_obj_set_size(root, S2_SCREEN_W, S2_SCREEN_H);
    lv_obj_set_pos(root, 0, 0);
    lv_obj_set_style_bg_color(root, lv_color_hex(S2_COL_BG), LV_PART_MAIN);
    lv_obj_set_style_border_width(root, 0, LV_PART_MAIN);
    lv_obj_set_style_pad_all(root, 0, LV_PART_MAIN);
    lv_obj_remove_flag(root, LV_OBJ_FLAG_SCROLLABLE);

    /* §3.2: the 56 px system bar is fixed and not configurable. It carries the
     * clock, which changes every second in the real firmware and is therefore
     * part of the steady-state render cost. */
    lv_obj_t *bar = lv_obj_create(root);
    lv_obj_set_size(bar, S2_SCREEN_W, S2_BAR_H);
    lv_obj_set_pos(bar, 0, 0);
    lv_obj_set_style_bg_color(bar, lv_color_hex(S2_COL_SURFACE), LV_PART_MAIN);
    lv_obj_set_style_border_width(bar, 0, LV_PART_MAIN);
    lv_obj_set_style_radius(bar, 0, LV_PART_MAIN);
    lv_obj_remove_flag(bar, LV_OBJ_FLAG_SCROLLABLE);

    lv_obj_t *clock = lv_label_create(bar);
    lv_label_set_text(clock, "22:41");
    lv_obj_set_style_text_font(clock, &slate_font_body_20, LV_PART_MAIN);
    lv_obj_set_style_text_color(clock, lv_color_hex(S2_COL_TEXT_HI), LV_PART_MAIN);
    lv_obj_align(clock, LV_ALIGN_LEFT_MID, 0, 0);

    lv_obj_t *title = lv_label_create(bar);
    lv_label_set_text_fmt(title, "Page %u", (unsigned)(index + 1));
    lv_obj_set_style_text_font(title, &slate_font_body_20, LV_PART_MAIN);
    lv_obj_set_style_text_color(title, lv_color_hex(S2_COL_TEXT_HI), LV_PART_MAIN);
    lv_obj_center(title);

    lv_obj_t *wifi = s2_icon_label(bar, S2_ICON_WIFI_STRENGTH_4, false, S2_COL_TEXT_LO);
    lv_obj_align(wifi, LV_ALIGN_RIGHT_MID, 0, 0);

    /*
     * Build tag. Not decoration: this spike's pass criterion is what a person
     * sees, and visual judgements were twice nearly recorded against the wrong
     * build because the panel had been reflashed between the question and the
     * answer. The tag makes "which one am I looking at" answerable from the
     * panel itself rather than from the order of events in a chat.
     *
     * It hangs off the root rather than off the system bar. Putting a fourth
     * child in the bar disturbed the bar's own layout — the page title stopped
     * sitting where it belongs — and an instrument that changes the thing it is
     * measuring is worse than no instrument. Here it overlaps nothing: the §3.2
     * grid ends 14 px above the bottom edge and this sits in that margin.
     */
    lv_obj_t *tag = lv_label_create(root);
    lv_label_set_text(tag, S2_BUILD_TAG);
    lv_obj_set_style_text_font(tag, &slate_font_caption_15, LV_PART_MAIN);
    lv_obj_set_style_text_color(tag, lv_color_hex(S2_COL_ACCENT), LV_PART_MAIN);
    lv_obj_align(tag, LV_ALIGN_BOTTOM_RIGHT, -2, 0);

    /*
     * Tiles are laid out cell by cell, and the page always ends up with exactly
     * S2_TILES tiles — the count is the variable under test, so a multi-cell
     * tile eating a neighbour's cell would quietly measure a smaller page than
     * the one being reported.
     *
     * The rule: a recipe gets its §3.2 size only while the grid can still spare
     * the cells; from the moment the tiles left to place equal the cells left
     * free, everything is 1×1. Saturating a 4 × 3 grid with twelve tiles
     * therefore means twelve 1×1 tiles, which is not a simplification but what
     * §3.2 forces — twelve is only reachable at the smallest size. Lower counts
     * leave room and produce the mixed pages the size variants in §7 describe.
     */
    bool occupied[S2_GRID_ROWS][S2_GRID_COLS];
    memset(occupied, 0, sizeof(occupied));
    uint32_t free_cells = S2_GRID_ROWS * S2_GRID_COLS;

    /* §13 asks for four animated tiles; the selection is inside the loop. */
    uint32_t animated_so_far = 0;

    for (uint32_t i = 0; i < S2_TILES; i++) {
        const s2_recipe_t *r = &S2_RECIPES[(i + index * 3) % S2_RECIPE_COUNT];

        int col = -1, row = -1;
        uint8_t tw = 1, th = 1;
        for (int rr = 0; rr < S2_GRID_ROWS && row < 0; rr++) {
            for (int cc = 0; cc < S2_GRID_COLS && row < 0; cc++) {
                if (occupied[rr][cc]) {
                    continue;
                }
                col = cc;
                row = rr;

                const uint32_t tiles_left = S2_TILES - i;
                if (free_cells <= tiles_left) {
                    break; /* every remaining tile needs a cell of its own */
                }
                bool fits = (cc + r->w <= S2_GRID_COLS) && (rr + r->h <= S2_GRID_ROWS) &&
                            (free_cells - (uint32_t)(r->w * r->h) >= tiles_left - 1);
                for (int y = rr; fits && y < rr + r->h; y++) {
                    for (int x = cc; fits && x < cc + r->w; x++) {
                        fits = !occupied[y][x];
                    }
                }
                if (fits) {
                    tw = r->w;
                    th = r->h;
                }
            }
        }
        if (row < 0) {
            break; /* grid full — only possible if S2_TILES exceeds the cells */
        }
        free_cells -= (uint32_t)(tw * th);
        for (int y = row; y < row + th; y++) {
            for (int x = col; x < col + tw; x++) {
                occupied[y][x] = true;
            }
        }

        const int32_t w = tw * S2_CELL_W + (tw - 1) * S2_GAP;
        const int32_t h = th * S2_CELL_H + (th - 1) * S2_GAP;
        const int32_t x = S2_MARGIN + col * (S2_CELL_W + S2_GAP);
        const int32_t y = S2_BAR_H + S2_MARGIN + row * (S2_CELL_H + S2_GAP);

        s2_tile_t *t = &s_tiles[s_tile_count];
        t->type = r->type;
        t->tile = lv_obj_create(root);
        lv_obj_set_size(t->tile, w, h);
        lv_obj_set_pos(t->tile, x, y);
        lv_obj_set_style_bg_color(t->tile, lv_color_hex(S2_COL_SURFACE), LV_PART_MAIN);
        lv_obj_set_style_radius(t->tile, S2_RADIUS, LV_PART_MAIN);
        lv_obj_set_style_border_width(t->tile, 0, LV_PART_MAIN);
        lv_obj_set_style_pad_all(t->tile, S2_MARGIN, LV_PART_MAIN);
        lv_obj_remove_flag(t->tile, LV_OBJ_FLAG_SCROLLABLE);

        /*
         * The issue asks for four animated tiles, and getting this wrong
         * under-loads the whole measurement.
         *
         * The first version picked every fifth tile — indices 0, 5, 10, 15 —
         * without noticing that only light and cover have an animated variant
         * (§7.1 pending pulse, §7.2 movement indicator); sensor and scene
         * ignore the flag. On the twelve-tile page those indices land on one
         * light and three tiles that cannot animate, so the scene ran with
         * **one** animation instead of four and every frame-time number was
         * measured against a lighter load than §13 specifies.
         *
         * Counting only the tiles that can actually animate fixes it. The
         * symptom that exposed it was rendering *gaps*: with almost nothing
         * moving, LVGL correctly drew nothing for 100-300 ms at a time, which
         * a frame-time percentile cannot show because a frame that was never
         * rendered is not in the sample.
         */
        const bool animated = (r->type == S2_LIGHT || r->type == S2_COVER) &&
                              animated_so_far < S2_ANIMATED_TILES;
        if (animated) {
            animated_so_far++;
        }

        s2_recipe_t sized = *r;
        sized.w = tw;
        sized.h = th;

        switch (r->type) {
        case S2_LIGHT:   s2_build_light(t, w, h, &sized, animated); break;
        case S2_COVER:   s2_build_cover(t, w, h, &sized, animated); break;
        case S2_SENSOR:  s2_build_sensor(t, w, &sized); break;
        case S2_SCENE:   s2_build_scene(t, w, &sized); break;
        default:         s2_build_unknown(t, &sized); break;
        }
        s_tile_count++;
    }

    return root;
}

void s2_scene_destroy(lv_obj_t *root)
{
    /* Deleting a tree with animations still attached is the case §6.4 has to
     * survive and the one S-1 measured for leaks; here it is simply the switch
     * path being timed. */
    lv_obj_delete(root);
    memset(s_tiles, 0, sizeof(s_tiles));
    s_tile_count = 0;
}

/* -------------------------------------------------------------------------
 * Entity updates (§5.2) — 10 per second
 * ------------------------------------------------------------------------- */

void s2_scene_update(uint32_t seq)
{
    if (s_tile_count == 0) {
        return;
    }
    s2_tile_t *t = &s_tiles[seq % s_tile_count];

    switch (t->type) {
    case S2_SENSOR:
        if (t->value) {
            /*
             * §7.5 out-of-range: every tenth update is a four-digit reading, so
             * the type scale steps down and the label re-lays out at a different
             * size. That is a heavier update than changing a digit, and a real
             * dashboard with a pressure sensor has one on screen permanently.
             */
            char buf[16];
            if ((seq % 10) == 0) {
                snprintf(buf, sizeof(buf), "1013.%u", (unsigned)(seq % 10));
                lv_obj_set_style_text_font(t->value, &slate_font_body_20, LV_PART_MAIN);
            } else {
                snprintf(buf, sizeof(buf), "%u.%u", (unsigned)(18 + seq % 9),
                         (unsigned)(seq % 10));
                lv_obj_set_style_text_font(t->value, &slate_font_hero_44, LV_PART_MAIN);
            }
            lv_label_set_text(t->value, buf);
        }
        break;

    case S2_LIGHT:
        if (t->slider) {
            const int32_t pct = (int32_t)(seq * 7 % 101);
            lv_slider_set_value(t->slider, pct, LV_ANIM_OFF);
            if (t->value) {
                lv_label_set_text_fmt(t->value, "%d%%", (int)pct);
            }
        } else if (t->icon) {
            lv_obj_set_style_text_color(t->icon,
                                        lv_color_hex((seq % 2) ? S2_COL_WARN : S2_COL_TEXT_LO),
                                        LV_PART_MAIN);
        }
        break;

    case S2_COVER:
        if (t->bar) {
            lv_bar_set_value(t->bar, (int32_t)(seq * 3 % 101), LV_ANIM_OFF);
        }
        break;

    default:
        /* Scenes are stateless (§7.4) and the placeholder has nothing to show.
         * Both are left alone deliberately: a real page has tiles that never
         * update, and counting them as updated would overstate the load. */
        break;
    }
}

uint32_t s2_scene_tile_count(void)
{
    return s_tile_count;
}
