/*
 * The device token, as §4.3 delivers it.
 *
 * It arrives in the fragment of the pairing QR URL —
 * `http://192.168.1.42/#t=Xk7p…` — so it is not sent in the HTTP request. It is
 * kept in localStorage and taken out of the address bar as soon as it has been
 * claimed. Query-string links from older firmware remain accepted.
 */

const STORAGE_KEY = 'slate.device_token'

/** §4.3's token: 32 characters drawn from the URL-safe base64 alphabet. */
const TOKEN_PATTERN = /^[A-Za-z0-9_-]{32}$/

export function isToken(value: string): boolean {
  return TOKEN_PATTERN.test(value)
}

/**
 * A token out of anything a person can reasonably hand this field: the token
 * itself, or the whole pairing URL they copied out of a phone that scanned the
 * QR and then would not open the page.
 */
export function parseToken(input: string): string | null {
  const trimmed = input.trim()
  if (isToken(trimmed)) {
    return trimmed
  }
  try {
    const url = new URL(trimmed)
    const fromFragment = new URLSearchParams(url.hash.slice(1)).get('t')
    if (fromFragment !== null && isToken(fromFragment)) {
      return fromFragment
    }
    const fromQuery = url.searchParams.get('t')
    return fromQuery !== null && isToken(fromQuery) ? fromQuery : null
  } catch {
    return null
  }
}

export function readStoredToken(): string | null {
  try {
    const stored = window.localStorage.getItem(STORAGE_KEY)
    return stored !== null && isToken(stored) ? stored : null
  } catch {
    /* Private browsing, or storage denied for this origin. The editor still
     * works for as long as the tab is open; it just pairs again next time. */
    return null
  }
}

export function storeToken(token: string): void {
  try {
    window.localStorage.setItem(STORAGE_KEY, token)
  } catch {
    /* See above. Not being able to remember the token is not a reason to
     * refuse to use it. */
  }
}

export function forgetToken(): void {
  try {
    window.localStorage.removeItem(STORAGE_KEY)
  } catch {
    /* Nothing to do: there was nothing to forget. */
  }
}

/**
 * Claim the token from `#t=` and take it out of the address bar. The `?t=`
 * form is a compatibility path for pairing links generated by older firmware.
 *
 * Returns it whether or not the URL is rewritten — a page opened from a
 * `file://` origin or an old browser that refuses `replaceState` should still
 * pair.
 */
export function claimTokenFromUrl(): string | null {
  const url = new URL(window.location.href)
  const fragment = new URLSearchParams(url.hash.slice(1))
  const fragmentToken = fragment.get('t')
  const queryToken = url.searchParams.get('t')
  const token = fragmentToken !== null && isToken(fragmentToken)
    ? fragmentToken
    : queryToken !== null && isToken(queryToken)
      ? queryToken
      : null
  if (token === null) {
    return null
  }

  storeToken(token)
  try {
    url.searchParams.delete('t')
    fragment.delete('t')
    const remainingFragment = fragment.toString()
    url.hash = remainingFragment === '' ? '' : `#${remainingFragment}`
    window.history.replaceState(null, '', url.pathname + url.search + url.hash)
  } catch {
    /* The token is stored; a URL that still shows it is worse than this catch
     * but better than not pairing. */
  }
  return token
}
