/*
 * Slate — clock: SNTP and the timezone.
 *
 * design.md §3.3 (`settings.timezone`, the night schedule), §6.1 (SNTP in the
 * stack), §9.4 (why the clock cannot be set in setup mode).
 *
 *
 * WHY SNTP DOES NOT START AT BOOT
 *
 * A panel on its own access point has no route to an NTP server, and §9 makes
 * that a state a device can legitimately spend a week in. So the sync starts
 * on IP_EVENT_STA_GOT_IP, not in app_main, and this component subscribes to
 * #8's SLATE_WIFI_EVENT_CONNECTED rather than being driven from there — the
 * station has no business knowing what a clock is.
 *
 * The consequence is a window, at every cold boot and for the whole of setup
 * mode, in which the device does not know what time it is. slate_time_synced()
 * is how the rest of the firmware finds that out, and both callers of it are
 * required rather than optional:
 *
 *   - §6's system bar shows no clock rather than 01:00 on 1 January 1970.
 *   - §3.3's night schedule does not act. A panel that spent a week in setup
 *     mode must not dim itself because an unsynced clock happens to fall
 *     inside `night_start`..`night_end`.
 *
 *
 * WHERE THE TIMEZONE COMES FROM
 *
 * §3.3 puts `timezone` in the configuration document, whose parser is #19. So
 * this component takes it through slate_time_set_timezone() and defaults to
 * UTC until something calls it. Persisting a copy in NVS would give one
 * setting two sources of truth that disagree the moment a configuration is
 * imported (§10), which is a worse failure than a clock that is briefly in the
 * wrong zone.
 */

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <time.h>

#include "esp_err.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Long enough for `America/Argentina/ComodRivadavia`, the longest name in the
 * generated table, with room to spare. */
#define SLATE_TIME_ZONE_MAX_LEN 40

/** @brief The zone in force before anything sets one. */
#define SLATE_TIME_DEFAULT_ZONE "UTC"

/**
 * @brief Apply the default zone and arrange for SNTP to start on association.
 *
 * Call once from app_main. Order against slate_wifi_init() does not matter:
 * this subscribes to the default event loop, and a station that is already
 * connected when it subscribes is handled — see the note in slate_time.c.
 */
esp_err_t slate_time_init(void);

/**
 * @brief Set the timezone from an IANA zone name — `Europe/Warsaw`.
 *
 * Resolved against the table generated by tools/tz/generate.sh and applied to
 * the process TZ, so localtime_r() and strftime() are correct from the next
 * call.
 *
 * ESP_ERR_NOT_FOUND for a name the table does not carry, in which case the
 * previous zone stays in force. A configuration naming an unknown zone is
 * §3.1's "unknown fields are ignored" applied to a value: the dashboard is
 * still worth showing with the clock an hour out, and #19 should surface the
 * name rather than reject the document.
 */
esp_err_t slate_time_set_timezone(const char *iana);

/** @brief The IANA name currently in force. Never NULL. */
const char *slate_time_timezone(void);

/**
 * @brief Whether the clock has been set from the network since boot.
 *
 * False means the device does not know what time it is — see the header
 * comment for the two things that must not happen while it is.
 */
bool slate_time_synced(void);

/**
 * @brief Convert an epoch value using the configured timezone.
 *
 * Serialized with timezone changes so the clock and brightness scheduler
 * cannot observe newlib's process-wide TZ state while it is being replaced.
 */
bool slate_time_localtime(time_t value, struct tm *out);

#ifdef __cplusplus
}
#endif
